package de.jp.infoprojekt.gameengine.state;

public enum GameState {

    DEV(1000),
    GAME_ENTRY(1),
    INTRODUCTION_CALLING(2),
    INTRODUCTION_CALL(3),

    MISSION_REFUSED(7), // -> Game END
    MISSION_REFUSED_DOOR_KNOCKED(8), // -> Game END
    MISSION_REFUSED_DOOR_ANSWERED(9),
    GAME_OVER(10),

    GAME_INTRODUCED(11),
    CHOOSING_RECIPE(12),

    FIRST_NITRIC_ACID(13),
    FIRST_SULFURIC_ACID(14),
    CLICKED_SALPETER_HYPERLINK(15),


    GO_TO_FARMER(16),
    EARNING_MONEY(17),

    CREATE_OXYGEN(18),
    GET_ELECTROLYSIS(19),
    PLACE_ELECTROLYSIS(20),
    PLACED_ELECTROLYSIS(21),

    GET_SALPTERGEN(22),
    PLACE_SALPTERGEN(23),
    PLACED_SALPTERGEN(24),
    GOT_NITRIC_ACID(25),
    GOT_NITRIC_ACID_DIALOG(26),
    BUY_SULFURIC_ACID(27),


    BOUGHT_SULFURIC_ACID(35),

    NEED_COLA(36),
    DRANK_COLA(37),

    REMEMBER_FOG_FLUID(38),

    BUY_FOG_FLUID(39),
    BOUGHT_FOG_FLUID(40),
    GET_DISTILLATION_DEVICE(41),
    PLACE_DISTILLATION_DEVICE(42),
    PLACED_DISTILLATION_DEVICE(43),
    CREATED_GLYCERIN(44),

    GET_NITRATOR(45),
    PLACE_NITRATOR(46),
    PLACED_NITRATOR(47),

    CREATED_NITRO_GLYCERIN(48),
    CREATED_NITRO_GLYCERIN_DIALOG(49),
    DRINK_COLA(50),
    GO_TO_REST(51),
    RESTED(52),
    PLACED_BOMB(53),

    BOMB_EXPLODED(54),
    CALL_G(55),
    CALLING_G(56);

    private final int id;

    GameState(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

}
